#!/bin/bash 

find ./tttt -type f > file;

IFS=$'\n'       # make newlines the only separator
set -f          # disable globbing
for i in $(cat file); do
  gpg -e -a -u  "Dimitar" -r "devops-jenkins@lovethis.com" ./$i;
done

